spring.application.name=svc-oms
server.port=8083

# H2 en mémoire (profil dev)
spring.datasource.url=jdbc:h2:mem:omsdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true

# Logging
logging.level.com.docapost.oms=DEBUG

# OMS externe simulée (MVP)
oms.api.base-url=http://localhost:9090/api/oms
oms.api.enabled=false

# Outbox poller — toutes les 10 secondes
oms.outbox.polling-delay-ms=10000
