/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Palette Material Design 3 — DocuPost Design System
        'primary':                   '#0037b0',
        'primary-container':         '#1d4ed8',
        'on-primary':                '#ffffff',
        'on-primary-container':      '#cad3ff',
        'primary-fixed':             '#dce1ff',
        'primary-fixed-dim':         '#b7c4ff',
        'on-primary-fixed':          '#001551',
        'on-primary-fixed-variant':  '#0039b5',
        'secondary':                 '#4d5b94',
        'secondary-container':       '#b0befe',
        'on-secondary':              '#ffffff',
        'on-secondary-container':    '#3d4c83',
        'secondary-fixed':           '#dce1ff',
        'secondary-fixed-dim':       '#b7c4ff',
        'on-secondary-fixed':        '#03164d',
        'on-secondary-fixed-variant':'#35437b',
        'tertiary':                  '#7f2500',
        'tertiary-container':        '#a73400',
        'tertiary-fixed':            '#ffdbcf',
        'tertiary-fixed-dim':        '#ffb59c',
        'on-tertiary':               '#ffffff',
        'on-tertiary-container':     '#ffc9b7',
        'on-tertiary-fixed':         '#390c00',
        'on-tertiary-fixed-variant': '#832700',
        'error':                     '#ba1a1a',
        'error-container':           '#ffdad6',
        'on-error':                  '#ffffff',
        'on-error-container':        '#93000a',
        'surface-container-lowest':  '#ffffff',
        'surface-container-low':     '#f2f4f6',
        'surface-container':         '#eceef0',
        'surface-container-high':    '#e6e8ea',
        'surface-container-highest': '#e0e3e5',
        'surface-bright':            '#f7f9fb',
        'surface-dim':               '#d8dadc',
        'surface-variant':           '#e0e3e5',
        'on-surface':                '#191c1e',
        'on-surface-variant':        '#434655',
        'on-background':             '#191c1e',
        'outline':                   '#747686',
        'outline-variant':           '#c4c5d7',
        'background':                '#f7f9fb',
        'surface':                   '#f7f9fb',
        'surface-tint':              '#2151da',
        'inverse-surface':           '#2d3133',
        'inverse-on-surface':        '#eff1f3',
        'inverse-primary':           '#b7c4ff',
      },
      fontFamily: {
        'headline': ['Work Sans', 'sans-serif'],
        'body':     ['Inter', 'sans-serif'],
        'label':    ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        'sm':    '0.125rem',
        'md':    '0.25rem',
        'lg':    '0.25rem',
        'xl':    '0.5rem',
        '2xl':   '0.75rem',
        'full':  '9999px',
      },
    },
  },
  plugins: [require('daisyui')],
  daisyui: {
    themes: false,
    base: false,
    styled: true,
    utils: true,
  },
};
